---
efiSystemPartition: "/boot/efi"
drawNestedPartitions: false
alwaysShowPartitionLabels: true
efi:
    minimumSize: 260MiB
userSwapChoices:
    - none
    - suspend
defaultFileSystemType: btrfs
directoryFilesystemRestrictions:
    - directory: "/"
      allowedFilesystemTypes: ["btrfs", "f2fs", "ext4", "xfs"]
    - directory: "efi"
      allowedFilesystemTypes: ["fat32"]
      onlyWhenMountpoint: true
