.\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH buildtree 1 "19 June 2026" "" ""
.SH NAME
buildtree \- buildtree is used to sync the garuda and arch package build tree. 
.SH SYNOPSIS
'nh
.fi
.ad l
\fBbuildtree\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[OPTIONS]\&...
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
\fBbuildtree\fR is used to sync package trees. 
.PP
With buildtree, you can sync the garuda and arch linux packae build trees.
.SH OPTIONS
The following options are understood:
.TP 
\*(T<\fB\-s\fR\*(T>
Sync garuda linux tree.
.TP 
\*(T<\fB\-a\fR\*(T>
Sync Arch linux tree.
.TP 
\*(T<\fB\-c\fR\*(T>
Clean package trees.
.TP 
\*(T<\fB\-q\fR\*(T>
Query settings.
.TP 
\*(T<\fB\-h\fR\*(T>
Help.
.SH "SEE ALSO"
\fBgaruda-tools.conf\fR(5),
