.\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH check-yaml 1 "19 June 2026" "" ""
.SH NAME
check-yaml \- check-yaml is used to generate and validate yaml files used by calamares. 
.SH SYNOPSIS
'nh
.fi
.ad l
\fBcheck-yaml\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[OPTIONS]\&...
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
\fBcheck-yaml\fR is used to generate and validate yaml files used by calamares.
.PP
check-yaml is a script to generate and validate yaml files by yaml schemas. Buildiso generates these files also, but check-yaml is a standalone version without the need to build the entire iso.
.SH OPTIONS
The following options are understood:
.TP 
\*(T<\fB\-p PROFILE...\fR\*(T>
Name of the build list or name of the directory.
.TP 
\*(T<\fB\-a i686|x86_64\fR\*(T>
Architecture that the yaml will be created for. Can be i686 or x86_64.
.TP 
\*(T<\fB\-k linuxXXX\fR\*(T>
The kernel the yaml will be created for.
.TP 
\*(T<\fB\-c\fR\*(T>
Create calamares yaml conf files.
.TP 
\*(T<\fB\-g\fR\*(T>
Generate a packman group netgroup yaml file.
.TP 
\*(T<\fB\-v\fR\*(T>
Validate the yaml file by yaml schema.
.TP 
\*(T<\fB\-q\fR\*(T>
Query settings.
.TP 
\*(T<\fB\-h\fR\*(T>
Help.
.SH "SEE ALSO"
\fBgaruda-tools.conf\fR(5),
\fBprofiles.conf\fR(5),
