.\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH deployiso 1 "19 June 2026" "" ""
.SH NAME
deployiso \- deployiso is used to upload a particular ISO or a set of ISOs. 
.SH SYNOPSIS
'nh
.fi
.ad l
\fBdeployiso\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[OPTIONS]\&...
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
\fBdeployiso\fR is used to upload a particular ISO or a set of ISOs. 
.PP
deployiso is a script to upload a specific iso or a buiildset to SF.
.SH OPTIONS
The following options are understood:
.TP 
\*(T<\fB\-d\fR\*(T>
Use hidden remote directory.
The target directory name will be prefaced with a dot.
.TP 
\*(T<\fB\-h\fR\*(T>
Help.
.TP 
\*(T<\fB\-l\fR\*(T>
Limit bandwidth in kB/s.
.TP 
\*(T<\fB\-p PROFILE...\fR\*(T>
Name of the build list or name of the directory
you will upload.
.TP 
\*(T<\fB\-q\fR\*(T>
Query settings and pretend upload.
.TP 
\*(T<\fB\-s\fR\*(T>
Sign ISO and create checksums before uploading.
.TP 
\*(T<\fB\-t\fR\*(T>
Create a torrent from iso file.
.TP 
\*(T<\fB\-u\fR\*(T>
Update remote iso.
.TP 
\*(T<\fB\-v\fR\*(T>
Verbose output.
.SH "SEE ALSO"
\fBgaruda-tools.conf\fR(5),
\fBprofiles.conf\fR(5),
